# Generated by Django 3.2.7 on 2023-09-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Executor',
            new_name='Perfomer',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='executor',
            new_name='perfomer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='executor',
        ),
        migrations.AddField(
            model_name='song',
            name='perfomer',
            field=models.ManyToManyField(to='api.Perfomer'),
        ),
    ]
