# Generated by Django 3.2.7 on 2023-09-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230913_2236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfomer',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='perfomer',
            new_name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='perfomer',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='api.Artist'),
        ),
    ]
